CREATE TABLE SETTINGS(
    SITE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SITE_NAME VARCHAR(150),
    SITE_SUBTITLE VARCHAR(200),
    SITE_URL TEXT,
    SITE_MAX_POSTS INTEGER
);
CREATE TABLE POSTS(
    POST_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    POST_TITLE VARCHAR(200),
    POST_TEXT TEXT,
    TAGS TEXT,
    SITE_ID INTEGER NOT NULL,
    FOREIGN KEY(SITE_ID) REFERENCES SETTINGS(SITE_ID)
);